#@name CREATE NEW OFFER
POST {{baseUrl}}/offers/ HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "Билли Саммерс",
  "description": "У нас тут все ништяк. Ларек за углом. Шава 24 часа. Приезжайте! Интернетов нет!",
  "postDate": "2021-02-01T11:56:37.573Z",
  "city": "Paris",
  "isPremium": true,
  "lodging": "apartment",
  "roomsCount": 2,
  "guestsCount": 6,
  "price": 75161,
  "features": ["Washer","Towels","Fridge"],
  "hostId": "63dbe04c9d4c8f2da57f6ffe",
  "location": {
    "latitude": 40.88414,
    "longitude": 142.793509
    }
}
> {% client.global.set("offerId", response.body.id); %}
###

#@name GET OFFERS BY QUERY
GET {{baseUrl}}/offers?count=60&city=Brussels&premium=true HTTP/1.1
###

#@name GET OFFER BY ID
GET {{baseUrl}}/offers/{{offerId}} HTTP/1.1
###

#@name GET OFFER COMMERNTS
GET {{baseUrl}}/offers/{{offerId}}/comments HTTP/1.1
###

#@name UPDATE OFFER
PATCH {{baseUrl}}/offers/{{offerId}} HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "Небольшая лавочка в парке!!!",
  "description": "Тут красиво, светло и уютно. Есть где разместиться компании из 5 человек. Кофе и печеньки бесплатно.",
  "price": 1100
}
###
#@name UPLOAD OFFER IMAGES
POST {{baseUrl}}/offers/{{offerId}}/images  HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=WebKitFormBoundary

--WebKitFormBoundary
Content-Disposition: form-data; name="preview"; filename="room-small.jpg"
Content-Type: image/jpeg

< ../markup/img/room-small.jpg
--WebKitFormBoundary--
Content-Disposition: form-data; name="photos"; filename="room.jpg"
Content-Type: image/jpeg

< ../markup/img/room.jpg
--WebKitFormBoundary--
Content-Disposition: form-data; name="photos"; filename="apartment-01.jpg"
Content-Type: image/jpeg

< ../markup/img/apartment-01.jpg
--WebKitFormBoundary--
Content-Disposition: form-data; name="photos"; filename="apartment-02.jpg"
Content-Type: image/jpeg

< ../markup/img/apartment-02.jpg
--WebKitFormBoundary--
Content-Disposition: form-data; name="photos"; filename="apartment-03.jpg"
Content-Type: image/jpeg

< ../markup/img/apartment-03.jpg
--WebKitFormBoundary--
Content-Disposition: form-data; name="photos"; filename="apartment-02.jpg"
Content-Type: image/jpeg

< ../markup/img/apartment-02.jpg
--WebKitFormBoundary--
Content-Disposition: form-data; name="photos"; filename="apartment-03.jpg"
Content-Type: image/jpeg

< ../markup/img/apartment-03.jpg
--WebKitFormBoundary--
###
#@name DELETE OFFER
DELETE {{baseUrl}}/offers/{{offerId}} HTTP/1.1
Authorization: Bearer {{accessToken}}
###
