#@name REGISTER NEW USER
POST {{baseUrl}}/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Jack",
  "email": "toranss@overlook.net",
  "isPro": true,
  "password": "123456"
}
> {%
  client.global.set("userId", response.body.id);
%}
###
#@name USER LOGIN
POST {{baseUrl}}/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "freedom@pisem.local",
  "password": "123456"
}
###
#@name UPLOAD AVATAR IMAGE
  POST {{baseUrl}}/users/63d968fe50a3b653408f09cf/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=WebKitFormBoundary

--WebKitFormBoundary
Content-Disposition: form-data; name="avatar"; filename="avatar-angelina.jpg"
Content-Type: image/jpeg

< ../markup/img/avatar-angelina.jpg
--WebKitFormBoundary--
#Content-Disposition: form-data; name="avatar"; filename="avatar-max.jpg"
#Content-Type: image/png
#
#< ../markup/img/avatar-max.jpg
#--WebKitFormBoundary--
#Content-Disposition: form-data; name="avatar"; filename="avatar-max.jpg"
#Content-Type: image/png
#
#< ../markup/img/avatar-max.jpg
#--WebKitFormBoundary--
###
